version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: campus_mate_db
    environment:
      POSTGRES_DB: campus_mate
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d campus_mate"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: